import 'package:shelf/shelf.dart';

/// Middleware that adds the 'Reporting-Endpoints' header to HTML responses.
///
/// This header tells the browser where to send reports generated by the
/// Reporting API.
Middleware reportingHeaders() {
  return (Handler innerHandler) {
    return (Request request) async {
      final response = await innerHandler(request);

      // Only add the header to successful HTML responses
      final contentType = response.headers['content-type'] ?? '';
      if (response.statusCode == 200 && contentType.contains('text/html')) {
        return response.change(
          headers: {'Reporting-Endpoints': 'default="/_reports/default"'},
        );
      }

      return response;
    };
  };
}
